##- name: Wait for MySQL container to become ready
##  wait_for:
##    host: "localhost"
##    port: 3307
##    delay: 20
##    timeout: 120
#
#
#- name: Copy MySQL dump to container
#  shell: docker cp "/home/ubuntu/sgt2023_group3_final_assignment/people_db_backup.sql" "mysql:/var/lib/people_db_backup.sql"
#
#
#- name: Import people_db_backup.sql into MySQL container
#  shell: docker exec -i "mysql" bash -c 'cat /var/lib/mysql | mysql -u root -pICanDoIt! db'
#  args:
#    executable: /bin/bash
#
- name: Wait for MySQL container to become ready
  wait_for:
    host: "localhost"
    port: 3307
    delay: 20
    timeout: 120


- name: Copy MySQL dump to container
  shell: docker cp "/home/ubuntu/sgt2023_group3_final_assignment/people_db_backup.sql" "mysql:/var/lib/people_db_backup.sql"


- name: Import people_db_backup.sql into MySQL container
  shell: docker exec -i "mysql" bash -c 'cat /var/lib/mysql | mysql -u root -pICanDoIt! people'
  args:
    executable: /bin/bash