version: '3'

services:
  db:
    image: mysql:latest
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: people
      MYSQL_ROOT_PASSWORD: ICanDoIt!
    ports:
      - '3307:3306'
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      mysql-network:
        aliases:
          - mysql

  app:
    build: ./python-app
    container_name: python
    depends_on:
      - db
    restart: always
    ports:
      - '8000:8000'
    networks:
      - mysql-network

networks:
  mysql-network:
    driver: bridge
volumes:
  mysql-data:
    driver: local
